[project]
name = "llm-inference-lab0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.15.0",
    "safetensors>=0.8.0",
    "torch>=2.14.0",
    "transformers>=5.17.0",
]

[project.scripts]
llm-inference-lab0 = "llm_inference_lab0:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
